keyboard:
  matrix_positions:
    # Left Hand
    # Pinky (columns 1-3)
    - [[2,1],  [1,2],  [2,2],  [3,2],  [2,3],    # Left pinky (north, west, center, east, south)
    # Ring (columns 4-6)
      [5,1],  [4,2],  [5,2],  [6,2],  [5,3],    # Left ring
    # Middle (columns 7-9)
      [8,1],  [7,2],  [8,2],  [9,2],  [8,3],    # Left middle
    # Index (columns 10-12)
      [11,1], [10,2], [11,2], [12,2], [11,3],   # Left index
    # Right Hand
    # Index (columns 13-15)
      [14,1], [13,2], [14,2], [15,2], [14,3],   # Right index
    # Middle (columns 16-18)
      [17,1], [16,2], [17,2], [18,2], [17,3],   # Right middle
    # Ring (columns 19-21)
      [20,1], [19,2], [20,2], [21,2], [20,3],   # Right ring
    # Pinky (columns 22-24)
      [23,1], [22,2], [23,2], [24,2], [23,3]]   # Right pinky

    # Thumb clusters (sequential numbering)
    - [[2,4],  [3,4],  [4,4],  [5,4],            # Left thumb cluster
      [20,4], [21,4], [22,4], [23,4]]           # Right thumb cluster

  positions:
    # Left Hand
    # Pinky (columns 1-3)
    - [[2,1],  [1,2],  [2,2],  [3,2],  [2,3],    # Left pinky (north, west, center, east, south)
    # Ring (columns 4-6)
      [5,1],  [4,2],  [5,2],  [6,2],  [5,3],    # Left ring
    # Middle (columns 7-9)
      [8,1],  [7,2],  [8,2],  [9,2],  [8,3],    # Left middle
    # Index (columns 10-12)
      [11,1], [10,2], [11,2], [12,2], [11,3],   # Left index
    # Right Hand
    # Index (columns 13-15)
      [14,1], [13,2], [14,2], [15,2], [14,3],   # Right index
    # Middle (columns 16-18)
      [17,1], [16,2], [17,2], [18,2], [17,3],   # Right middle
    # Ring (columns 19-21)
      [20,1], [19,2], [20,2], [21,2], [20,3],   # Right ring
    # Pinky (columns 22-24)
      [23,1], [22,2], [23,2], [24,2], [23,3]]   # Right pinky

    # Thumb clusters (sequential numbering)
    - [[2,4],  [3,4],  [4,4],  [5,4],            # Left thumb cluster
      [20,4], [21,4], [22,4], [23,4]]           # Right thumb cluster

  hands:
    # Main key rows (rows 1-3)
    - [Left, Left, Left, Left, Left,      # Left pinky positions
       Left, Left, Left, Left, Left,      # Left ring positions
       Left, Left, Left, Left, Left,      # Left middle positions
       Left, Left, Left, Left, Left,      # Left index positions
       Right, Right, Right, Right, Right, # Right index positions
       Right, Right, Right, Right, Right, # Right middle positions
       Right, Right, Right, Right, Right, # Right ring positions
       Right, Right, Right, Right, Right] # Right pinky positions
    
    # Thumb row (row 4)
    - [Left, Left, Left, Left,            # Left thumb cluster
       Right, Right, Right, Right]        # Right thumb cluster

  fingers:
    - [Pinky, Pinky, Pinky, Pinky, Pinky,   # Left pinky positions
       Ring, Ring, Ring, Ring, Ring,         # Left ring positions
       Middle, Middle, Middle, Middle, Middle, # Left middle positions
       Index, Index, Index, Index, Index,     # Left index positions
       Index, Index, Index, Index, Index,     # Right index positions
       Middle, Middle, Middle, Middle, Middle, # Right middle positions
       Ring, Ring, Ring, Ring, Ring,         # Right ring positions
       Pinky, Pinky, Pinky, Pinky, Pinky]   # Right pinky positions
    
    # Thumb row (row 4)
    - [Thumb, Thumb, Thumb, Thumb,           # Left thumb cluster
       Thumb, Thumb, Thumb, Thumb]           # Right thumb cluster

  key_costs:
      # N    W   C   E   S
      - [5,  6,  3,  5,  3,     # Left pinky
        4,   8,  2,  5,  2,     # Left ring
        4,   7,  2,  5,  2,     # Left middle
        4,   5,  2,  4,  2,     # Left index
        4,   4,  2,  5,  2,     # Right index
        4,   5,  2,  7,  2,     # Right middle
        4,   5,  2,  8,  2,     # Right ring
        5,   5,  3,  6,  3]     # Right pinky
      
      # Thumb row (row 4)
      - [2, 3, 2, 2,            # Left thumb cluster
        2, 3, 2, 2]            # Right thumb cluster

  unbalancing_positions:
    # Main key rows (rows 1-3)
    - [[0, 0], [0, 0], [0,0], [0,5], [0, 0],     # Left pinky
      [0, 0], [0, 0], [0, 0], [0, 10], [0, 0],     # Left ring
      [0, 0], [0, 0], [0, 0], [0, 0], [0, 0],     # Left middle
      [0, 0], [0, 0], [0, 0], [0, 0], [0, 0],     # Left index
      [0, 0], [0, 0], [0, 0], [0, 0], [0, 0],     # Right index
      [0, 0], [0, 0], [0, 0], [0, 0], [0, 0],     # Right middle
      [0, 0], [0, 10], [0, 0], [0, 0], [0, 0],     # Right ring
      [0, 0], [0, 5], [0, 0], [0, 0], [0, 0]]     # Right pinky
    
    # Thumb row (row 4)
    - [[0, 0], [0, 0], [0, 0], [0, 0],             # Left thumb cluster
      [0, 0], [0, 0], [0, 0], [0, 0]]             # Right thumb cluster

  symmetries:
    # Main key rows (rows 1-3)
    - [1, 2, 3, 4, 5,         # Left pinky
      6, 7, 8, 9, 10,        # Left ring
      11, 12, 13, 14, 15,    # Left middle
      16, 17, 18, 19, 20,    # Left index
      20, 19, 18, 17, 16,    # Right index (mirrored)
      15, 14, 13, 12, 11,    # Right middle (mirrored)
      10, 9, 8, 7, 6,        # Right ring (mirrored)
      5, 4, 3, 2, 1]         # Right pinky (mirrored)
    
    # Thumb row (row 4)
    - [21, 22, 23, 24,        # Left thumb cluster
      24, 23, 22, 21]        # Right thumb cluster (mirrored)

  finger_resting_positions:
    Left:
      Pinky: [50.5, 115.5]
      Ring: [100.5, 115.5]
      Middle: [150.5, 115.5]
      Index: [200.5, 115.5]
      Thumb: [230.5, 210.5]
    Right:
      Pinky: [650.5, 115.5]
      Ring: [600.5, 115.5]
      Middle: [550.5, 115.5]
      Index: [500.5, 115.5]
      Thumb: [470.5, 210.5]


  plot_template: |2
                LEFT HAND                                                            RIGHT HAND

       {{0}}        {{5}}          {{10}}          {{15}}                                    {{20}}        {{25}}          {{30}}          {{35}}
     {{1}} {{2}} {{3}}    {{6}} {{7}} {{8}}      {{11}} {{12}} {{13}}      {{16}} {{17}} {{18}}                                {{21}} {{22}} {{23}}    {{26}} {{27}} {{28}}      {{31}} {{32}} {{33}}      {{36}} {{37}} {{38}}
       {{4}}        {{9}}          {{14}}          {{19}}                                    {{24}}        {{29}}          {{34}}          {{39}}
       

                                          LEFT THUMB        RIGHT THUMB
                                          {{40}} {{41}}                  {{44}} {{45}}
                                          {{42}} {{43}}                  {{46}} {{47}}


  plot_template_short: |2
    {{0}}{{1}}{{2}}{{3}}{{4}}{{5}} {{6}}{{7}}{{8}}{{9}}{{10}}{{11}}
    ⇘{{12}}{{13}}{{14}}{{15}}{{16}} {{17}}{{18}}{{19}}{{20}}{{21}}⇘
     {{22}}{{23}}{{24}}{{25}}{{26}} {{27}}{{28}}{{29}}{{30}}{{31}}

base_layout:
  keys:
      # Main key rows (rows 1-3)
      - [["a"], ["b"], ["c"], ["d"], ["e"],     # Left pinky
        ["f"], ["g"], ["h"], ["i"], ["j"],     # Left ring
        ["k"], ["l"], ["m"], ["n"], ["o"],     # Left middle
        ["p"], ["q"], ["r"], ["s"], ["t"],     # Left index
        ["u"], ["v"], ["w"], ["x"], ["y"],     # Right index
        ["z"], ["0"], ["1"], ["2"], ["3"],     # Right middle
        ["4"], ["5"], ["6"], ["7"], ["8"],     # Right ring
        ["9"], ["="], ["{"], ["}"], ["("]]     # Right pinky
      
      # Thumb row (row 4)
      - [[" "], [""], [""], [""],            # Left thumb cluster
        ["["], [""], [""], [""]]            # Right thumb cluster

  fixed_keys:
    # Main key rows (rows 1-3)
    - [false, false, false, false, false,     # Left pinky
       false, false, false, false, false,     # Left ring
       false, false, false, false, false,     # Left middle
       false, false, false, false, false,     # Left index
       false, false, false, false, false,     # Right index
       false, false, false, false, false,     # Right middle
       false, false, false, false, false,     # Right ring
       false, false, false, false, false]     # Right pinky
    
    # Thumb row (row 4)
    - [true, true, true, true,                # Left thumb cluster
       false, true, true, true]                # Right thumb cluster

  # for NeoLayoutGenerator:
  # layers that shall not be permutated (starting from 0)
  fixed_layers: []

  # for GroupedLayoutGenerator:
  # number of consecutive symbols from base layout to group together generating a layout
  grouped_layers: 1

  # modifier types can be "hold", "one_shot", and "long_press"
  #
  # "hold" and "one_shot" modifiers require a field "value" holding a list of
  # either matrix positions or symbols acting as modifiers
  modifiers:
    - Left:
        type: hold
        value: []
      Right:
        type: hold
        value: []
